### ISSUE TITLE
Hide Avatar doesn't Work

### ISSUE THREAD

**Issue by 007sg** [02-t/BetterChess-com#3]
When enable hide avatar, it doesn't work. Please see image.
![sshot-825](https://user-images.githubusercontent.com/19493298/213404260-19047704-5efb-4cce-9e98-ca988586302f.jpg)

This is the error
![sshot-824](https://user-images.githubusercontent.com/19493298/213403931-95263af6-83a0-4b3c-83c4-bd686d96c6e0.jpg)

**Comment by 02-t** [comment]
Thank you for reporting the bug! It has been fixed in the latest release [https://github.com/02-t/BetterChess-com/releases/tag/v1.2c](https://github.com/02-t/BetterChess-com/releases/tag/v1.2c)
